/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonFooter: typeof import('./src/components/common/common-footer.vue')['default']
    CommonLayout: typeof import('./src/components/common/common-layout.vue')['default']
    Header: typeof import('./src/components/Layout/component/header.vue')['default']
    Info: typeof import('./src/components/Layout/component/info.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Menusider: typeof import('./src/components/Layout/component/menusider.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NotFound: typeof import('./src/components/NotFound/index.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTableColumns: typeof import('naive-ui')['NTableColumns']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
