/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Layout/component/header.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Menu: typeof import('./src/components/Layout/component/menu.vue')['default']
    Menusider: typeof import('./src/components/Layout/component/menusider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NotFound: typeof import('./src/components/NotFound/index.vue')['default']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
